;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        easy-kill
        electric-newline-and-maybe-indent
        elpy-nav-indent-shift-left
        elpy-nav-indent-shift-right
        end-of-buffer
        indent-for-tab-command
        ivy-switch-buffer
        org-cycle
        org-demote-subtree
        org-self-insert-command
        save-some-buffers
        sp-up-sexp
        xref-find-definitions
        ))

(setq mc/cmds-to-run-once
      '(
        anzu-query-replace
        ))
